import type { BlackHoleVacuumTuning } from '../blackHole';
import type { ShipId } from '../../data/ships';
import type { WeaponId } from '../../data/weapons';
import type { EncounterDefinitionId } from '../../data/encounters';
import type {
  DebugCollisionShapeScaleKey,
  DebugImpactSourceType,
  DebugPhysicsTuningKey,
  DebugShipStatKey,
  DebugWeaponStatKey
} from './debugState';
import type { DeathShardStyle, DeathShardTuningKey } from '../deathEffects';

export type DebugEnemyType = 'chaser' | 'shooter' | 'tank';
export type DebugAsteroidTier = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
export type DebugPlayerTeleportTarget = 'center' | 'mission' | 'extraction' | 'blackHole';

export interface DebugMenuValues {
  runTimeSeconds: number;
  selectedShipName: string;
  activeWeaponName: string;
  playerXp: number;
  nextXpThreshold: number;
  bankedUpgrades: number;
  enemySpawningEnabled: boolean;
  asteroidSpawningAvailable: boolean;
  asteroidSpawningEnabled: boolean;
  playerInvulnerable: boolean;
  collisionDebugEnabled: boolean;
  blackHoleRadiiVisible: boolean;
  blackHoleFieldDamageEnabled: boolean;
  weaponDamageMultiplier: number;
  weaponFireRateMultiplier: number;
  weaponCooldownSeconds: number;
  backgroundStarsVisible: boolean;
  starfieldFarParallax: number;
  starfieldMidParallax: number;
  starfieldNearParallax: number;
  blackHoleInfluenceRadiusScale: number;
  blackHoleDamageRadiusScale: number;
  blackHoleVisualScale: number;
  blackHoleCoreScale: number;
  blackHoleRadialStrengthMultiplier: number;
  blackHoleRadialCurve: number;
  blackHoleSwirlStrengthMultiplier: number;
  blackHoleSwirlCurve: number;
  blackHoleMaxVelocityMultiplier: number;
  blackHoleViscosityStrength: number;
  blackHoleViscosityCurve: number;
  blackHoleInnerDrag: number;
  blackHolePlayerResistance: number;
  blackHoleActive: boolean;
  blackHoleX: number;
  blackHoleY: number;
  blackHoleRunAgeSeconds: number;
  blackHoleEventHorizonRadius: number;
  blackHoleCaptureRadius: number;
  blackHoleWarningRadius: number;
  blackHoleGrowthPercent: number;
  blackHolePlayerCaptured: boolean;
  blackHoleCaptureTimerRemainingMs: number;
  blackHoleConsumedObjects: number;
  blackHolePlayerCaptureEnabled: boolean;
  blackHoleObjectConsumptionEnabled: boolean;
  blackHoleWarningVisualsEnabled: boolean;
  blackHoleBaseEventHorizonRadius: number;
  blackHoleMaxEventHorizonRadius: number;
  blackHoleGrowthPerMinute: number;
  blackHoleCaptureMargin: number;
  blackHoleWarningMargin: number;
  blackHolePlayerCaptureDurationMs: number;
  blackHolePlayerPullStrength: number;
  blackHoleObjectPullStrength: number;
  debugGamePaused: boolean;
  performanceProfilerEnabled: boolean;
  performanceProfilerManualActive: boolean;
  performanceProfilerSummary: string;
  autoDiagnosticsEnabled: boolean;
  autoDiagnosticsActive: boolean;
  autoDiagnosticsSummary: string;
  activeEnemies: number;
  activeAsteroids: number;
  asteroidFragmentSoftCap: number;
  asteroidFragmentHardCap: number;
  asteroidFragmentBurstLimit: number;
  debugAsteroidSpawnCount: number;
  activeDebris: number;
  activeScrapPickups: number;
  runScrapTotal: number;
  runScrapSpent: number;
  totalCredits: number;
  nextRerollCost: number;
  debugRerollCostBase: number;
  playerProjectiles: number;
  enemyProjectiles: number;
  playerHull: number;
  playerMaxHull: number;
  playerAlive: boolean;
  playerX: number;
  playerY: number;
  playerVelocityX: number;
  playerVelocityY: number;
  playerCollisionDamageImmune: boolean;
  missionObjectiveDistance: number;
  extractionDistance: number;
  secretControlUnlocked: boolean;
  fuel: number;
  fuelMax: number;
  fuelDrainEnabled: boolean;
  fuelDrainMode: string;
  playerSpeed: number;
  playerMaxSpeed: number;
  playerThrust: number;
  playerBrake: number;
  playerStrafe: number;
  playerThrustScale: number;
  playerBrakeScale: number;
  playerStrafeScale: number;
  playerInertiaScale: number;
  enemySpeedScale: number;
  enemyResponseScale: number;
  asteroidCollisionDamageScale: number;
  asteroidCollisionImpulseScale: number;
  globalMaxSpeed: number;
  globalImpactDamageCap: number;
  playerImpactDamageCap: number;
  enemyImpactDamageCap: number;
  asteroidImpactDamageCap: number;
  debrisImpactDamageCap: number;
  playerImpactDamageScale: number;
  enemyImpactDamageScale: number;
  asteroidImpactDamageScale: number;
  debrisImpactDamageScale: number;
  healthBarsEnabled: boolean;
  playerHealthBarEnabled: boolean;
  healthBarRevealOnPlayerDamage: boolean;
  healthBarWidthScale: number;
  healthBarHeight: number;
  healthBarVerticalOffset: number;
  healthBarAlpha: number;
  damageNumbersEnabled: boolean;
  damageNumberSourceColorsEnabled: boolean;
  damageNumberFontSize: number;
  damageNumberLifetimeMs: number;
  damageNumberRiseDistance: number;
  damageNumberDrift: number;
  damageNumberScalePop: number;
  damageNumberFadeStart: number;
  damageNumberAlpha: number;
  asteroidDamageFlashEnabled: boolean;
  collisionShapeTuningSummary: string;
  rammingShieldHp: number;
  rammingShieldMaxHp: number;
  rammingShieldDashCharges: number;
  rammingShieldDashMaxCharges: number;
  shipTuningSummaries: Record<ShipId, string>;
  weaponTuningSummaries: Record<WeaponId, string>;
  deathShardTuningSummaries: Record<DeathShardStyle, string>;
  spawnDirectorSummary: string;
}

export interface DebugMenuCallbacks {
  close: () => void;
  saveDebugPreset: () => void;
  loadDebugPreset: () => void;
  resetDebugTuning: () => void;
  toggleDebugPause: () => void;
  togglePerformanceProfiler: () => void;
  startPerformanceCapture: () => void;
  stopPerformanceCapture: () => void;
  exportPerformanceReport: () => void;
  clearPerformanceProfiler: () => void;
  openReportsFolder: () => void;
  openDataFolder: () => void;
  toggleAutoDiagnostics: () => void;
  writeAutoDiagnosticReportNow: () => void;
  openCurrentRunDiagnosticsFolder: () => void;
  openRunsFolder: () => void;
  toggleEnemySpawning: () => void;
  spawnEnemy: (type: DebugEnemyType) => void;
  spawnEncounter: (id: EncounterDefinitionId) => void;
  clearEnemies: () => void;
  toggleAsteroidSpawning: () => void;
  spawnAsteroid: (tier: DebugAsteroidTier) => void;
  clearAsteroids: () => void;
  adjustAsteroidFragmentSoftCap: (delta: number) => void;
  adjustAsteroidFragmentHardCap: (delta: number) => void;
  adjustAsteroidFragmentBurstLimit: (delta: number) => void;
  setAsteroidFragmentSoftCap: (value: number) => void;
  setAsteroidFragmentHardCap: (value: number) => void;
  setAsteroidFragmentBurstLimit: (value: number) => void;
  adjustDebugAsteroidSpawnCount: (delta: number) => void;
  setDebugAsteroidSpawnCount: (value: number) => void;
  resetDebugAsteroidSpawnCount: () => void;
  resetAsteroidFragmentTuning: () => void;
  spawnDebris: () => void;
  clearDebris: () => void;
  spawnScrap: () => void;
  clearScrap: () => void;
  addScrap: (amount: number) => void;
  addCredits: (amount: number) => void;
  toggleRerollDebugCost: () => void;
  clearPlayerProjectiles: () => void;
  clearEnemyProjectiles: () => void;
  restorePlayerHull: () => void;
  healPlayer: (amount: number) => void;
  damagePlayerForDebug: (amount: number) => void;
  togglePlayerInvulnerability: () => void;
  togglePlayerCollisionDamageImmunity: () => void;
  killPlayer: () => void;
  stopPlayerVelocity: () => void;
  teleportPlayer: (target: DebugPlayerTeleportTarget) => void;
  nudgePlayer: (dx: number, dy: number) => void;
  addPlayerXp: (amount: number) => void;
  addBankedUpgrade: (amount: number) => void;
  clearBankedUpgrades: () => void;
  resetWeaponCooldowns: () => void;
  refillRammingShield: () => void;
  unlockSecretControls: () => void;
  refillFuel: () => void;
  emptyFuel: () => void;
  toggleFuelDrain: () => void;
  toggleFuelDrainMode: () => void;
  adjustPlayerThrustScale: (delta: number) => void;
  adjustPlayerBrakeScale: (delta: number) => void;
  adjustPlayerStrafeScale: (delta: number) => void;
  adjustPlayerInertiaScale: (delta: number) => void;
  adjustEnemySpeedScale: (delta: number) => void;
  adjustEnemyResponseScale: (delta: number) => void;
  adjustAsteroidCollisionDamageScale: (delta: number) => void;
  adjustAsteroidCollisionImpulseScale: (delta: number) => void;
  adjustGlobalMaxSpeed: (delta: number) => void;
  adjustGlobalImpactDamageCap: (delta: number) => void;
  adjustImpactDamageCap: (source: DebugImpactSourceType, delta: number) => void;
  adjustImpactDamageScale: (source: DebugImpactSourceType, delta: number) => void;
  setPhysicsTuning: (key: DebugPhysicsTuningKey, value: number) => void;
  resetPhysicsTuning: () => void;
  toggleHealthBars: () => void;
  togglePlayerHealthBar: () => void;
  toggleHealthBarRevealOnPlayerDamage: () => void;
  adjustHealthBarWidthScale: (delta: number) => void;
  adjustHealthBarHeight: (delta: number) => void;
  adjustHealthBarVerticalOffset: (delta: number) => void;
  adjustHealthBarAlpha: (delta: number) => void;
  toggleDamageNumbers: () => void;
  toggleDamageNumberSourceColors: () => void;
  toggleAsteroidDamageFlash: () => void;
  adjustDamageNumberFontSize: (delta: number) => void;
  adjustDamageNumberLifetimeMs: (delta: number) => void;
  adjustDamageNumberRiseDistance: (delta: number) => void;
  adjustDamageNumberDrift: (delta: number) => void;
  adjustDamageNumberScalePop: (delta: number) => void;
  adjustDamageNumberFadeStart: (delta: number) => void;
  adjustDamageNumberAlpha: (delta: number) => void;
  resetCombatFeedbackTuning: () => void;
  adjustCollisionShapeScale: (key: DebugCollisionShapeScaleKey, delta: number) => void;
  setCollisionShapeScale: (key: DebugCollisionShapeScaleKey, value: number) => void;
  resetCollisionShapeTuning: () => void;
  adjustDeathShardTuning: (style: DeathShardStyle, key: DeathShardTuningKey, delta: number) => void;
  setDeathShardTuning: (style: DeathShardStyle, key: DeathShardTuningKey, value: number) => void;
  resetDeathShardTuning: () => void;
  testDeathShardEffect: (style: DeathShardStyle) => void;
  adjustWeaponDamage: (delta: number) => void;
  adjustWeaponFireRate: (delta: number) => void;
  adjustWeaponCooldownSeconds: (deltaSeconds: number) => void;
  resetWeaponTuning: () => void;
  adjustShipLoadoutStat: (shipId: ShipId, stat: DebugShipStatKey, delta: number) => void;
  setShipLoadoutStat: (shipId: ShipId, stat: DebugShipStatKey, value: number) => void;
  resetShipLoadout: (shipId: ShipId) => void;
  saveShipLoadout: (shipId: ShipId) => void;
  loadShipLoadout: (shipId: ShipId) => void;
  adjustWeaponLoadoutStat: (weaponId: WeaponId, stat: DebugWeaponStatKey, delta: number) => void;
  setWeaponLoadoutStat: (weaponId: WeaponId, stat: DebugWeaponStatKey, value: number) => void;
  resetWeaponLoadout: (weaponId: WeaponId) => void;
  saveWeaponLoadout: (weaponId: WeaponId) => void;
  loadWeaponLoadout: (weaponId: WeaponId) => void;
  adjustStarfieldParallax: (layer: 'far' | 'mid' | 'near', direction: number) => void;
  toggleBackgroundStars: () => void;
  resetStarfieldParallax: () => void;
  toggleBlackHoleRadii: () => void;
  toggleBlackHoleFieldDamage: () => void;
  toggleCollisionDebug: () => void;
  toggleBlackHolePlayerCapture: () => void;
  toggleBlackHoleObjectConsumption: () => void;
  toggleBlackHoleWarningVisuals: () => void;
  moveBlackHoleToPlayer: () => void;
  moveBlackHoleAwayFromPlayer: () => void;
  resetBlackHoleGrowth: () => void;
  addBlackHoleGrowthMinutes: (minutes: number) => void;
  forceBlackHoleCaptureTest: () => void;
  forceBlackHoleEscapeTest: () => void;
  adjustBlackHoleVacuumTuning: (key: keyof BlackHoleVacuumTuning, delta: number) => void;
  adjustBlackHoleInfluenceRadius: (delta: number) => void;
  adjustBlackHoleDamageRadius: (delta: number) => void;
  adjustBlackHoleVisualScale: (delta: number) => void;
  adjustBlackHoleCoreScale: (delta: number) => void;
  adjustBlackHoleRadialStrength: (delta: number) => void;
  adjustBlackHoleRadialCurve: (delta: number) => void;
  adjustBlackHoleSwirlStrength: (delta: number) => void;
  adjustBlackHoleSwirlCurve: (delta: number) => void;
  adjustBlackHoleMaxVelocity: (delta: number) => void;
  adjustBlackHoleViscosityStrength: (delta: number) => void;
  adjustBlackHoleViscosityCurve: (delta: number) => void;
  adjustBlackHoleInnerDrag: (delta: number) => void;
  adjustBlackHolePlayerResistance: (delta: number) => void;
  saveBlackHoleFieldTuning: () => void;
  loadBlackHoleFieldTuning: () => void;
  resetBlackHoleTuning: () => void;
}
