import type { BlackHolePngLayerDebugSummary, BlackHolePngTextureKey } from '../blackHole';

export type DebugEnemyType = 'chaser' | 'shooter' | 'tank';
export type DebugAsteroidTier = 1 | 2 | 3 | 4 | 5;

export interface DebugMenuValues {
  enemySpawningEnabled: boolean;
  asteroidSpawningAvailable: boolean;
  asteroidSpawningEnabled: boolean;
  playerInvulnerable: boolean;
  collisionDebugEnabled: boolean;
  blackHoleRadiiVisible: boolean;
  blackHoleFieldDamageEnabled: boolean;
  pulseDamageMultiplier: number;
  pulseFireRateMultiplier: number;
  pulseCooldownSeconds: number;
  backgroundStarsVisible: boolean;
  starfieldFarParallax: number;
  starfieldMidParallax: number;
  starfieldNearParallax: number;
  blackHoleLensOrbitSpeedMultiplier: number;
  blackHoleLensDensity: number;
  blackHoleLensLengthMultiplier: number;
  blackHoleInfluenceRadiusScale: number;
  blackHoleDamageRadiusScale: number;
  blackHoleVisualScale: number;
  blackHoleCoreScale: number;
  blackHoleRadialStrengthMultiplier: number;
  blackHoleRadialCurve: number;
  blackHoleSwirlStrengthMultiplier: number;
  blackHoleSwirlCurve: number;
  blackHoleMassResistanceMultiplier: number;
  blackHoleMaxVelocityMultiplier: number;
  blackHoleViscosityStrength: number;
  blackHoleViscosityCurve: number;
  blackHoleInnerDrag: number;
  blackHolePlayerResistance: number;
  blackHoleProjectionLensLayersEnabled: boolean;
  blackHoleSelectedPngLayerIndex: number;
  blackHolePngLayerCount: number;
  blackHoleSelectedPngLayer?: BlackHolePngLayerDebugSummary;
  blackHoleAddPngTextureKey: BlackHolePngTextureKey;
  blackHoleAddPngTextureLabel: string;
  debugGamePaused: boolean;
  activeEnemies: number;
  activeAsteroids: number;
  activeDebris: number;
  activeScrapPickups: number;
  runScrapTotal: number;
  totalCredits: number;
  playerProjectiles: number;
  enemyProjectiles: number;
  playerHull: number;
  playerMaxHull: number;
  spawnDirectorSummary: string;
}

export interface DebugMenuCallbacks {
  close: () => void;
  toggleDebugPause: () => void;
  toggleEnemySpawning: () => void;
  spawnEnemy: (type: DebugEnemyType) => void;
  clearEnemies: () => void;
  toggleAsteroidSpawning: () => void;
  spawnAsteroid: (tier: DebugAsteroidTier) => void;
  clearAsteroids: () => void;
  spawnDebris: () => void;
  clearDebris: () => void;
  spawnScrap: () => void;
  clearScrap: () => void;
  addScrap: (amount: number) => void;
  addCredits: (amount: number) => void;
  clearPlayerProjectiles: () => void;
  clearEnemyProjectiles: () => void;
  restorePlayerHull: () => void;
  togglePlayerInvulnerability: () => void;
  killPlayer: () => void;
  adjustPulseDamage: (delta: number) => void;
  adjustPulseFireRate: (delta: number) => void;
  adjustPulseCooldownSeconds: (deltaSeconds: number) => void;
  resetWeaponTuning: () => void;
  adjustStarfieldParallax: (layer: 'far' | 'mid' | 'near', direction: number) => void;
  toggleBackgroundStars: () => void;
  resetStarfieldParallax: () => void;
  toggleBlackHoleRadii: () => void;
  toggleBlackHoleFieldDamage: () => void;
  toggleCollisionDebug: () => void;
  adjustBlackHoleLensOrbit: (delta: number) => void;
  adjustBlackHoleLensLength: (delta: number) => void;
  adjustBlackHoleInfluenceRadius: (delta: number) => void;
  adjustBlackHoleDamageRadius: (delta: number) => void;
  adjustBlackHoleVisualScale: (delta: number) => void;
  adjustBlackHoleCoreScale: (delta: number) => void;
  adjustBlackHoleRadialStrength: (delta: number) => void;
  adjustBlackHoleRadialCurve: (delta: number) => void;
  adjustBlackHoleSwirlStrength: (delta: number) => void;
  adjustBlackHoleSwirlCurve: (delta: number) => void;
  adjustBlackHoleMassResistance: (delta: number) => void;
  adjustBlackHoleMaxVelocity: (delta: number) => void;
  adjustBlackHoleViscosityStrength: (delta: number) => void;
  adjustBlackHoleViscosityCurve: (delta: number) => void;
  adjustBlackHoleInnerDrag: (delta: number) => void;
  adjustBlackHolePlayerResistance: (delta: number) => void;
  toggleBlackHoleProjectionLenses: () => void;
  selectPreviousBlackHolePngLayer: () => void;
  selectNextBlackHolePngLayer: () => void;
  cycleBlackHolePngLayerImage: (direction: number) => void;
  cycleBlackHoleAddPngLayerImage: (direction: number) => void;
  adjustBlackHolePngLayerSpeed: (delta: number) => void;
  adjustBlackHolePngLayerSize: (delta: number) => void;
  adjustBlackHolePngLayerAlpha: (delta: number) => void;
  toggleBlackHolePngLayer: () => void;
  addBlackHolePngLayer: () => void;
  duplicateBlackHolePngLayer: () => void;
  removeBlackHolePngLayer: () => void;
  saveBlackHolePngSetup: () => void;
  loadBlackHolePngSetup: () => void;
  saveBlackHoleFieldTuning: () => void;
  loadBlackHoleFieldTuning: () => void;
  resetBlackHoleLensTuning: () => void;
}
